In [1]:
#import libraries
import pandas as pd
import json
import requests
import matplotlib
from pprint import pprint
from datetime import datetime, timedelta
import os
import csv

In [2]:
# url for GET requests to retrieve vaccination data
url="https://data.cdc.gov/resource/unsk-b7fc.json"
query_url="https://data.cdc.gov/resource/unsk-b7fc.json?$query=SELECT%0A%20%20%60date%60%2C%0A%20%20%60mmwr_week%60%2C%0A%20%20%60location%60%2C%0A%20%20%60distributed%60%2C%0A%20%20%60distributed_janssen%60%2C%0A%20%20%60distributed_moderna%60%2C%0A%20%20%60distributed_pfizer%60%2C%0A%20%20%60distributed_novavax%60%2C%0A%20%20%60distributed_unk_manuf%60%2C%0A%20%20%60dist_per_100k%60%2C%0A%20%20%60distributed_per_100k_5plus%60%2C%0A%20%20%60distributed_per_100k_12plus%60%2C%0A%20%20%60distributed_per_100k_18plus%60%2C%0A%20%20%60distributed_per_100k_65plus%60%2C%0A%20%20%60administered%60%2C%0A%20%20%60administered_5plus%60%2C%0A%20%20%60administered_12plus%60%2C%0A%20%20%60administered_18plus%60%2C%0A%20%20%60administered_65plus%60%2C%0A%20%20%60administered_janssen%60%2C%0A%20%20%60administered_moderna%60%2C%0A%20%20%60administered_pfizer%60%2C%0A%20%20%60administered_novavax%60%2C%0A%20%20%60administered_unk_manuf%60%2C%0A%20%20%60admin_per_100k%60%2C%0A%20%20%60admin_per_100k_5plus%60%2C%0A%20%20%60admin_per_100k_12plus%60%2C%0A%20%20%60admin_per_100k_18plus%60%2C%0A%20%20%60admin_per_100k_65plus%60%2C%0A%20%20%60recip_administered%60%2C%0A%20%20%60administered_dose1_recip%60%2C%0A%20%20%60administered_dose1_pop_pct%60%2C%0A%20%20%60administered_dose1_recip_5plus%60%2C%0A%20%20%60administered_dose1_recip_5pluspop_pct%60%2C%0A%20%20%60administered_dose1_recip_12plus%60%2C%0A%20%20%60administered_dose1_recip_12pluspop_pct%60%2C%0A%20%20%60administered_dose1_recip_18plus%60%2C%0A%20%20%60administered_dose1_recip_18pluspop_pct%60%2C%0A%20%20%60administered_dose1_recip_65plus%60%2C%0A%20%20%60administered_dose1_recip_65pluspop_pct%60%2C%0A%20%20%60series_complete_yes%60%2C%0A%20%20%60series_complete_pop_pct%60%2C%0A%20%20%60series_complete_5plus%60%2C%0A%20%20%60series_complete_5pluspop_pct%60%2C%0A%20%20%60series_complete_12plus%60%2C%0A%20%20%60series_complete_12pluspop%60%2C%0A%20%20%60series_complete_18plus%60%2C%0A%20%20%60series_complete_18pluspop%60%2C%0A%20%20%60series_complete_65plus%60%2C%0A%20%20%60series_complete_65pluspop%60%2C%0A%20%20%60series_complete_janssen%60%2C%0A%20%20%60series_complete_moderna%60%2C%0A%20%20%60series_complete_pfizer%60%2C%0A%20%20%60series_complete_novavax%60%2C%0A%20%20%60series_complete_unk_manuf%60%2C%0A%20%20%60series_complete_janssen_5plus%60%2C%0A%20%20%60series_complete_moderna_5plus%60%2C%0A%20%20%60series_complete_pfizer_5plus%60%2C%0A%20%20%60series_complete_unk_manuf_5plus%60%2C%0A%20%20%60series_complete_janssen_12plus%60%2C%0A%20%20%60series_complete_moderna_12plus%60%2C%0A%20%20%60series_complete_pfizer_12plus%60%2C%0A%20%20%60series_complete_unk_manuf_1%60%2C%0A%20%20%60series_complete_janssen_18plus%60%2C%0A%20%20%60series_complete_moderna_18plus%60%2C%0A%20%20%60series_complete_pfizer_18plus%60%2C%0A%20%20%60series_complete_unk_manuf_2%60%2C%0A%20%20%60series_complete_janssen_65plus%60%2C%0A%20%20%60series_complete_moderna_65plus%60%2C%0A%20%20%60series_complete_pfizer_65plus%60%2C%0A%20%20%60series_complete_unk_manuf_3%60%2C%0A%20%20%60additional_doses%60%2C%0A%20%20%60additional_doses_vax_pct%60%2C%0A%20%20%60additional_doses_5plus%60%2C%0A%20%20%60additional_doses_5plus_vax_pct%60%2C%0A%20%20%60additional_doses_12plus%60%2C%0A%20%20%60additional_doses_12plus_vax_pct%60%2C%0A%20%20%60additional_doses_18plus%60%2C%0A%20%20%60additional_doses_18plus_vax_pct%60%2C%0A%20%20%60additional_doses_50plus%60%2C%0A%20%20%60additional_doses_50plus_vax_pct%60%2C%0A%20%20%60additional_doses_65plus%60%2C%0A%20%20%60additional_doses_65plus_vax_pct%60%2C%0A%20%20%60additional_doses_moderna%60%2C%0A%20%20%60additional_doses_pfizer%60%2C%0A%20%20%60additional_doses_janssen%60%2C%0A%20%20%60additional_doses_unk_manuf%60%2C%0A%20%20%60second_booster%60%2C%0A%20%20%60second_booster_50plus%60%2C%0A%20%20%60second_booster_50plus_vax_pct%60%2C%0A%20%20%60second_booster_65plus%60%2C%0A%20%20%60second_booster_65plus_vax_pct%60%2C%0A%20%20%60second_booster_janssen%60%2C%0A%20%20%60second_booster_moderna%60%2C%0A%20%20%60second_booster_pfizer%60%2C%0A%20%20%60second_booster_unk_manuf%60%2C%0A%20%20%60administered_bivalent%60%2C%0A%20%20%60admin_bivalent_pfr%60%2C%0A%20%20%60admin_bivalent_mod%60%2C%0A%20%20%60dist_bivalent_pfr%60%2C%0A%20%20%60dist_bivalent_mod%60%2C%0A%20%20%60bivalent_booster_5plus%60%2C%0A%20%20%60bivalent_booster_5plus_pop_pct%60%2C%0A%20%20%60bivalent_booster_12plus%60%2C%0A%20%20%60bivalent_booster_12plus_pop_pct%60%2C%0A%20%20%60bivalent_booster_18plus%60%2C%0A%20%20%60bivalent_booster_18plus_pop_pct%60%2C%0A%20%20%60bivalent_booster_65plus%60%2C%0A%20%20%60bivalent_booster_65plus_pop_pct%60%0AWHERE%0A%20%20%60date%60%0A%20%20%20%20BETWEEN%20%222022-01-01T00%3A00%3A00%22%20%3A%3A%20floating_timestamp%0A%20%20%20%20AND%20%222022-12-31T00%3A00%3A00%22%20%3A%3A%20floating_timestamp"

In [42]:
#pretty print the output of json
response=requests.get(query_url).json()

In [18]:
#create data frame from json
original_data_frame=pd.DataFrame(response)
original_data_frame

,date,mmwr_week,location,distributed,distributed_janssen,distributed_moderna,distributed_pfizer,distributed_unk_manuf,dist_per_100k,distributed_per_100k_5plus,...,additional_doses_18plus,additional_doses_18plus_vax_pct,additional_doses_50plus,additional_doses_50plus_vax_pct,additional_doses_65plus,additional_doses_65plus_vax_pct,additional_doses_moderna,additional_doses_pfizer,additional_doses_janssen,additional_doses_unk_manuf
0,2022-01-01T00:00:00.000,52,LA,6872750,314500,2558900,3999350,0,147839,158091,...,731287,33.2,559008,44.9,350338,55.7,321754,403071,9900,29
1,2022-01-01T00:00:00.000,52,KS,5190675,249000,1942240,2999435,0,178171,190275,...,557370,36.8,394213,48.5,244567,58.3,251525,302076,8186,126
2,2022-01-01T00:00:00.000,52,OR,8477585,452300,3124020,4901265,0,200998,212475,...,1098338,42.9,727525,55.9,455089,66.6,486513,602397,17314,331
3,2022-01-01T00:00:00.000,52,MO,9887935,410500,3526700,5950735,0,161109,171387,...,1095320,36.4,802774,47.5,508817,58.1,458894,628057,13788,44
4,2022-01-01T00:00:00.000,52,AR,4989160,247500,1922840,2818820,0,165324,176337,...,465439,32.8,351295,44.3,227236,55.4,229849,229647,7598,401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2022-01-16T00:00:00.000,2,US,651561015,29887900,239546020,382127095,0,196248,208656,...,78868804,41.5,52315671,53.1,29894490,62,35543444,43505477,1195602,17813
996,2022-01-16T00:00:00.000,2,WI,10524275,449600,3911140,6163535,0,180754,191631,...,1781876,53.6,1228261,65.7,724972,76,774708,1008030,24599,72
997,2022-01-16T00:00:00.000,2,MH,68980,12100,47700,9180,0,88731,99685,...,2008,9.3,776,15,207,16.7,1990,13,8,0
998,2022-01-16T00:00:00.000,2,MS,4963115,218800,1972560,2771755,0,166763,177719,...,465867,34.3,365380,46.1,225313,56.3,223134,239309,6828,363
999,2022-01-16T00:00:00.000,2,RI,2402665,87000,902540,1413125,0,226803,239109,...,392079,52.8,253478,65.3,136803,74.4,175031,220592,4417,23

In [43]:
#organize the data frame with desired columns
vaccine_organized_data=original_data_frame[['location','administered']]
vaccine_organized_data

    location administered
0         LA      5671632
1         KS      4086457
2         OR      6852601
3         MO      8110832
4         AR      3800418
..       ...          ...
995       US    527903848
996       WI      9435461
997       MH        49506
998       MS      3584129
999       RI      2036182

[1000 rows x 2 columns]

In [36]:
state_mapping = {
    'AK': 'Alaska', 'AL': 'Alabama', 'AR': 'Arkansas', 'AZ': 'Arizona',
    'CA': 'California', 'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware',
    'FL': 'Florida', 'GA': 'Georgia', 'IA': 'Iowa', 'ID': 'Idaho',
    'IL': 'Illinois', 'IN': 'Indiana', 'KS': 'Kansas', 'KY': 'Kentucky',
    'LA': 'Louisiana', 'MA': 'Massachusetts', 'MD': 'Maryland', 'ME': 'Maine',
    'MI': 'Michigan', 'MN': 'Minnesota', 'MO': 'Missouri', 'MS': 'Mississippi',
    'MT': 'Montana', 'NC': 'North Carolina', 'ND': 'North Dakota', 'NE': 'Nebraska',
    'NH': 'New Hampshire', 'NJ': 'New Jersey', 'NM': 'New Mexico', 'NV': 'Nevada',
    'NY': 'New York', 'OH': 'Ohio', 'OK': 'Oklahoma', 'OR': 'Oregon',
    'PA': 'Pennsylvania', 'RI': 'Rhode Island', 'SC': 'South Carolina',
    'SD': 'South Dakota', 'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah',
    'VA': 'Virginia', 'VT': 'Vermont', 'WA': 'Washington', 'WI': 'Wisconsin',
    'WV': 'West Virginia', 'WY': 'Wyoming', 'HI':'Hawaii'}

In [48]:
# clean dataframe

copy_vaccine_organized_data=vaccine_organized_data.copy()
copy_vaccine_organized_data['administered'] = copy_vaccine_organized_data['administered'].astype(float) # changed str to float
copy_vaccine_organized_data = copy_vaccine_organized_data.groupby('location').sum() # do the sum
copy_vaccine_organized_data['State'] = copy_vaccine_organized_data.index.map(state_mapping)

#for index, rows in copy_vaccine_organized_data.iterrows():
#    print(rows['State']) # this was to print out every row's state.. we can see there are nans

copy_vaccine_organized_data = copy_vaccine_organized_data.dropna(how = 'any') # drop the nans
print(len(copy_vaccine_organized_data)) # to make sure we have 50 states
copy_vaccine_organized_data # print dataframe

50

          administered           State
location
AK        1.660524e+07          Alaska
AL        8.582507e+07         Alabama
AR        6.185417e+07        Arkansas
AZ        1.603667e+08         Arizona
CA        1.009724e+09      California
CO        1.548992e+08        Colorado
CT        1.090649e+08     Connecticut
DE        2.580014e+07        Delaware
FL        5.478387e+08         Florida
GA        2.032110e+08         Georgia
HI        3.802012e+07          Hawaii
IA        7.516150e+07            Iowa
ID        3.278174e+07           Idaho
IL        3.242109e+08        Illinois
IN        1.384811e+08         Indiana
KS        6.643119e+07          Kansas
KY        8.982229e+07        Kentucky
LA        9.193697e+07       Louisiana
MA        1.991069e+08   Massachusetts
MD        1.704197e+08        Maryland
ME        3.834861e+07           Maine
MI        2.275798e+08        Michigan
MN        1.394911e+08       Minnesota
MO        1.228162e+08        Missouri
MS        5.619587e+07     Mississippi
MT        2.334414e+07         Montana
NC        2.435258e+08  North Carolina
ND        1.540322e+07    North Dakota
NE        4.649762e+07        Nebraska
NH        3.912610e+07   New Hampshire
NJ        2.444681e+08      New Jersey
NM        5.594986e+07      New Mexico
NV        6.605481e+07          Nevada
NY        5.255039e+08        New York
OH        2.604420e+08            Ohio
OK        8.648367e+07        Oklahoma
OR        1.110876e+08          Oregon
PA        3.284963e+08    Pennsylvania
RI        3.195492e+07    Rhode Island
SC        1.025910e+08  South Carolina
SD        2.052171e+07    South Dakota
TN        1.358356e+08       Tennessee
TX        6.203929e+08           Texas
UT        7.351024e+07            Utah
VA        2.364420e+08        Virginia
VT        1.912256e+07         Vermont
WA        2.050857e+08      Washington
WI        1.486715e+08       Wisconsin
WV        4.041100e+07   West Virginia
WY        1.040140e+07         Wyoming